### ISSUE TITLE
Github API timeouts when uploading more than 10 reviews

### ISSUE THREAD

**Issue by jerry-skydio** [Skydio/revup#1]
When uploading more than 10 reviews, especially if creating or updating a large number, we occasionally see one of the mutation requests time out. This can usually be resolved by just rerunning the command, as a portion of the requests will have succeeded, making the remainder less likely to time out. 

Leaving this open to investigate a revup side fix or ask for github support / clarification.

**Comment by vlsi** [comment]
The best practice is making `one second` pauses between the requests: https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits

> If you're making a large number of POST, PATCH, PUT, or DELETE requests for a single user or client ID, **wait at least one second between each request**.
