### ISSUE TITLE
revup without modifying commit message?

### ISSUE THREAD

**Issue by myocytebd** [Skydio/revup#88]
**Is your feature request related to a problem? Please describe.**
Commit log would be cleaner if revup metadata is moved out of commit message.

**Describe the solution you'd like**
Local: maybe store in git notes?  
Github: maybe store in comments?  

**Describe alternatives you've considered**

**Comment by brian-kubisiak-skydio** [comment]
`revup upload` has the `--trim-tags` option which should accomplish this. The local commit (in your topic stack) still has the tags, but the commits pushed to github (and the PR message) do not.

You can make this the default by adding to your revup config:
```
[upload]
trim_tags = True
```

**Comment by myocytebd** [comment]
Good to know this feature.
